### ISSUE TITLE
A Better Pandas

### ISSUE THREAD

**Issue by idontgetoutmuch** [chrisdone/labels#1]
@chrisdone This is only tangentially to do with `labels`. I was trying to emulate http://tomaugspurger.github.io/modern-1.html in Haskell. Using his data set which is 113M, I thought I would start off by seeing what the headers are. I ran this in ghci:

```
main2 = do
  foo <- fmap decodeByName (LB.readFile "examples/787338586_T_ONTIME.csv")
  case foo of
    Right (header, rows :: Vector (Map String String)) -> do
      putStrLn $ show header
    Left err -> putStrLn err
```

This took a long time to run and used over 6G of memory eventually returning

```
*Main> main2
["FL_DATE","UNIQUE_CARRIER","AIRLINE_ID","TAIL_NUM","FL_NUM","ORIGIN_AIRPORT_ID","ORIGIN_AIRPORT_SEQ_ID","ORIGIN_CITY_MARKET_ID","ORIGIN","ORIGIN_CITY_NAME","ORIGIN_STATE_NM","DEST_AIRPORT_ID","DEST_AIRPORT_SEQ_ID","DEST_CITY_MARKET_ID","DEST","DEST_CITY_NAME","DEST_STATE_NM","CRS_DEP_TIME","DEP_TIME","DEP_DELAY","TAXI_OUT","WHEELS_OFF","WHEELS_ON","TAXI_IN","CRS_ARR_TIME","ARR_TIME","ARR_DELAY","CANCELLED","CANCELLATION_CODE","DIVERTED","DISTANCE","CARRIER_DELAY","WEATHER_DELAY","NAS_DELAY","SECURITY_DELAY","LATE_AIRCRAFT_DELAY",""]
```

Is there a better way of doing this? I'd quite like to write a Haskell equivalent of a pandas tutorial. Maybe we should create a separate repo for doing this and tracking how it is going.

**Comment by chrisdone** [comment]
@idontgetoutmuch It's not a bad idea; we could make a sort of repo for "R-equivalent" work.

In your case there is a streaming interface to cassava. I don't know whether it's obvious how to use it from the API. csv-conduit may be a bit easier.

**Comment by chrisdone** [comment]
See here: https://github.com/chrisdone/labels/tree/master/labels-explore
