### ISSUE TITLE
Generic instances?

### ISSUE THREAD

**Issue by jchia** [chrisdone/labels#12]
How can I easily get Generic instances for the `Labels` 'record' types? `Generic` is needed for deriving instances like `Hashable` and `ToJSON`.

If it can't be done easily, I suppose a workaround easily getting instances of things like `Hashable` is to use `Labels.reflect` and `GHC.Generics.from` to extract the field names and values `Rep`? Is there a better way?

**Comment by chrisdone** [comment]
I suspect it should be a case of adding an instance of Generic for `:=` and the rest follows.

**Comment by jchia** [comment]
Well, it turns out that labels being tuples, Generic is already derived for labels with up to 7 fields. Tuples with 8 elements or more don't get the Generic instance.

So, in order to get Generic instances for larger 'labels', I'll standalone-derive(orphaned) instances of Generic for 8- and larger tuples. Is there a better way?

**Comment by jchia** [comment]
The other issue as raised by @chrisdone still stands and is circumvented by explicitly making `Binary`, `Store`, etc instances for `:=`. `:=` is not a vanilla type so deriving `Generic` for it doesn't work.

**Comment by chrisdone** [comment]
Right, I think we can implement an instance of `Generic` manually, although I have never done so. You're welcome to take a crack at it and open a PR.
