### ISSUE TITLE
The examples are very slow to execute on Ubuntu

### ISSUE THREAD

**Issue by ghost** [chrisdone/labels#2]
The examples work and the code looks great, but the performance seems very poor.
Running
_time stack exec labels-explore-example_

gives on my laptop
flights  distance  
471949   3.7207249e8

real    0m54.148s
user    0m58.902s
sys 0m5.340s

**Comment by chrisdone** [comment]
Indeed -- we have a combination of:
1. The CSV parsing library doesn't support a more efficient parsing mode.
2. Conduit itself adds some overhead (although it's relatively negligible).

Unfortunately cassava parses every single row into a `HashMap ByteString ByteString` (or a `Vector ByteString`, depending on which class we use) before we're able to then convert it to our tuple, which causes _a lot_ of allocations.

But a much more efficient parser could be implemented, at the moment the code serves as a demonstration of how the code could be written only. Haskell is capable of much better, we would just have to allocate some time to do it.
