### ISSUE TITLE
cabal install labels-explore.cabal fails with error ?

### ISSUE THREAD

**Issue by jsmith50500** [chrisdone/labels#4]
Hi there was trying to follow your post 'Working with data in Haskell'  https://www.fpcomplete.com/blog/2016/09/data-haskell

So decided to pull the labels-master package down from here and went into each directory and did the following

cabal install labels.cabal (ran successfully to completion)
cabal install labels-cvs.cabal (ran successfully to completion)
cabal install labels-json.cabal (ran successfully to completion)
cabal install zip-conduit.cabal (ran successfully to completion)
cabal install http-client.cabal (ran successfully to completion)

when I ran cabal install labels-explore.cabal  (It fails, doesn't complete, the log says the following is wrong)

root@haskellbox~/.cabal/logs# cat labels-explore-0.1.0.0.log

---

cabal: Entering directory '.'
Configuring labels-explore-0.1.0.0...
Building labels-explore-0.1.0.0...
Preprocessing library labels-explore-0.1.0.0...
[1 of 1] Compiling Labels.Explore   ( src/Labels/Explore.hs, dist/build/Labels/Explore.o )

src/Labels/Explore.hs:26:5: error:
    Ambiguous occurrence ‘.|’
    It could refer to either ‘Data.Conduit..|’,
                             imported from ‘Data.Conduit’ at src/Labels/Explore.hs:72:1-29
                          or ‘Labels.Explore..|’, defined at src/Labels/Explore.hs:112:1
cabal: Leaving directory '.'

---

Can you help please would like to get this built so i can run the examples thank you

**Comment by chrisdone** [comment]
You have to use Stack for this.
