### ISSUE TITLE
FYI: Labels.Explore..| clashes with Data.Conduit..| for lts-8.19

### ISSUE THREAD

**Issue by alanz** [chrisdone/labels#7]
https://github.com/chrisdone/labels/blob/master/labels-explore/src/Labels/Explore.hs#L26

**Comment by chrisdone** [comment]
Right, fun fact: that operator `(.|)` arose in Conduit after discussing my `*.Explore` module with Michael.

This issue's fixed since https://github.com/chrisdone/labels/commit/fa4043f3d0ff5a4ed5c9bf513400d094113380f0#diff-843260347c43ee30fa23615c025762b7L110. Closing.
